2020-07-18 11:45:19,660: INFO: root: Starting main.py
2020-07-18 11:45:19,677: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 9, in __init__
    database.executeSqlQuery("CREATE TABLE IF NOT EXISTS Entity(entity_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, linked_entities INTEGER );")
  File "/mnt/d/Code Projects/telegram_bot_rpg/Database.py", line 12, in executeSqlQuery
    cursor.commit()
AttributeError: 'sqlite3.Cursor' object has no attribute 'commit'
2020-07-18 11:45:45,711: INFO: root: Starting main.py
2020-07-18 11:45:45,733: INFO: root: Done main.py
2020-07-18 11:45:51,361: INFO: root: Starting main.py
2020-07-18 11:45:51,383: INFO: root: Done main.py
2020-07-18 11:45:58,625: INFO: root: Starting main.py
2020-07-18 11:45:58,644: INFO: root: Done main.py
2020-07-18 11:45:59,429: INFO: root: Starting main.py
2020-07-18 11:45:59,448: INFO: root: Done main.py
2020-07-18 11:46:00,780: INFO: root: Starting main.py
2020-07-18 11:46:00,799: INFO: root: Done main.py
2020-07-18 11:47:00,453: INFO: root: Starting main.py
2020-07-18 11:47:00,764: INFO: root: Done main.py
2020-07-18 11:47:04,791: INFO: root: Starting main.py
2020-07-18 11:47:05,109: INFO: root: Done main.py
2020-07-18 11:47:12,379: INFO: root: Starting main.py
2020-07-18 11:47:12,669: INFO: root: Done main.py
2020-07-18 11:47:13,541: INFO: root: Starting main.py
2020-07-18 11:47:13,776: INFO: root: Done main.py
2020-07-18 11:51:19,430: INFO: root: Starting main.py
2020-07-18 11:51:19,449: INFO: root: Done main.py
2020-07-18 11:51:20,150: INFO: root: Starting main.py
2020-07-18 11:51:20,166: INFO: root: Done main.py
2020-07-18 11:51:24,897: INFO: root: Starting main.py
2020-07-18 11:51:24,915: INFO: root: Done main.py
2020-07-18 11:51:40,694: INFO: root: Starting main.py
2020-07-18 11:51:40,860: INFO: root: Done main.py
2020-07-18 11:51:45,314: INFO: root: Starting main.py
2020-07-18 11:51:45,486: INFO: root: Done main.py
2020-07-18 11:52:00,943: INFO: root: Starting main.py
2020-07-18 11:52:01,305: INFO: root: Done main.py
2020-07-18 12:30:42,781: INFO: root: Starting main.py
2020-07-18 12:30:42,797: INFO: root: Done main.py
2020-07-18 12:32:15,816: INFO: root: Starting main.py
2020-07-18 12:32:15,833: INFO: root: Done main.py
2020-07-18 12:33:00,533: INFO: root: Starting main.py
2020-07-18 12:33:00,548: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:01,739: INFO: root: Starting main.py
2020-07-18 12:33:01,752: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:27,366: INFO: root: Starting main.py
2020-07-18 12:33:27,385: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:33,462: INFO: root: Starting main.py
2020-07-18 12:33:33,479: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:34,310: INFO: root: Starting main.py
2020-07-18 12:33:34,325: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:34,954: INFO: root: Starting main.py
2020-07-18 12:33:34,971: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:35,570: INFO: root: Starting main.py
2020-07-18 12:33:35,582: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room")
TypeError: createEntity() missing 1 required positional argument: 'linkedEntity_ids'
2020-07-18 12:33:55,428: INFO: root: Starting main.py
2020-07-18 12:33:55,446: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 13, in __init__
    database.createEntity("Training Room", "A room", None)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Gamee/GameDatabase.py", line 38, in createEntity
    ent_list = self.createEntityList(linkedEntity_ids)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Gamee/GameDatabase.py", line 48, in createEntityList
    for ent_id in linkedEntity_ids:
TypeError: 'NoneType' object is not iterable
2020-07-18 12:34:59,081: INFO: root: Starting main.py
2020-07-18 12:34:59,221: INFO: root: Done main.py
2020-07-18 12:36:35,859: INFO: root: Starting main.py
2020-07-18 12:36:36,060: INFO: root: Done main.py
2020-07-18 12:36:51,072: INFO: root: Starting main.py
2020-07-18 12:36:51,325: INFO: root: Done main.py
2020-07-18 12:37:52,805: INFO: root: Starting main.py
2020-07-18 12:37:53,043: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 14, in __init__
    print(database.getAllEntityLists())
AttributeError: 'GameDatabase' object has no attribute 'getAllEntityLists'
2020-07-18 12:38:07,158: INFO: root: Starting main.py
2020-07-18 12:38:07,462: ERROR: root: 
Traceback (most recent call last):
  File "/mnt/d/Code Projects/telegram_bot_rpg/main.py", line 14, in <module>
    game = Game(game_db, telebot)
  File "/mnt/d/Code Projects/telegram_bot_rpg/Game.py", line 14, in __init__
    print(database.getAllEntityLists())
AttributeError: 'GameDatabase' object has no attribute 'getAllEntityLists'
2020-07-18 12:38:20,921: INFO: root: Starting main.py
2020-07-18 12:38:21,195: INFO: root: Done main.py
